version: '3'
services:
  app:
    build: ./app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - ./.env
    volumes:
     - ./app:/app
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
    env_file:
      - ./.env