apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: hello-world
  name: hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template: 
    metadata: 
      labels: 
        app: hello-world
    spec: 
      containers: 
        - image: "marcelodevops/hw:latest"
          imagePullPolicy: Always
          name: hw-container
          ports: 
            - containerPort: 8980
---
apiVersion: v1
kind: Service
metadata: 
  name: hello-world-svc
spec: 
  ports: 
     -  port: 8080
        protocol: TCP
        targetPort: 8980
  selector: 
    app: hello-world
  type: NodePort
