
---
- name: Create a new database with name apidb
  hosts: databases
  vars: 
    - login_user: "marce"
    - login_password: "Passw0rd"
    - mysql_root_password: "Passw0rd"
  remote_user: sa_104435124234002324598
  become: yes

  tasks:


  - name: create mysql database
    mysql_db:
      login_unix_socket: /var/lib/mysql/mysql.sock
      name: apidb
      state: present
      login_user: "{{login_user}}"
      login_password: "{{mysql_root_password}}"

  - name: mysql user login
    mysql_user:
      login_user: marce
      login_password: "{{mysql_root_password}}"
      name: marce
      host_all: yes     
      password: "{{mysql_root_password}}"

  - name: mysql dump database
    mysql_db:
      login_unix_socket: /var/lib/mysql/mysql.sock
      name: apidb
      state: dump
      target: /tmp/apidb.sql
      login_user: marce
      login_password: "{{mysql_root_password}}"   
  - name: check git is installed
    yum:
      name: git
      state: present
  
  - name: git clone repository code
    git:
      repo: https://github.com/marcelodevops/test-sre.git
      dest: /tmp/repos/test-sre
      update: yes
      version: master
  - name: install gpg
    yum: name=gpg state=present

  - name: copy backup sql into local repo and encrypt
    copy: 
      src: "/tmp/apidb.sql"  
      dest: "/tmp/repos/test-sre/"
      remote_src: yes

  - name: create cron job to perform db backups
    cron:
      name: "apidb hourly dump"
      minute: "0"
      hour: "*"
      job: "mysqldump apidb -u {{login_user}} -p{{login_password}} > /tmp/repos/test-sre/apidb.sql"


