
---
- name: Create a new database with name "{{mysql_db_name}}""
  hosts: databases
  remote_user: "{{ansible_remote_user}}"
  become: yes
  tasks:

  - include_vars: vars/vars.yml

  - name: create mysql database
    mysql_db:
      login_unix_socket: /var/lib/mysql/mysql.sock
      name: "{{mysql_db_name}}"
      state: present
      login_user: "{{login_user}}"
      login_password: "{{mysql_root_password}}"

  - name: mysql user login
    mysql_user:
      login_user: "{{login_user}}"
      login_password: "{{mysql_root_password}}"
      name: "{{login_user}}"
      host_all: yes     
      password: "{{mysql_root_password}}"

  - name: mysql dump database
    mysql_db:
      login_unix_socket: /var/lib/mysql/mysql.sock
      name: "{{mysql_db_name}}"
      state: dump
      target: /tmp/"{{mysql_db_name}}".sql
      login_user: "{{login_user}}"
      login_password: "{{mysql_root_password}}"   
  - name: check git is installed
    yum:
      name: git
      state: present
  
  - name: git clone repository code
    git:
      repo: https://github.com/marcelodevops/test-sre.git
      dest: /tmp/repos/test-sre
      update: yes
      version: "{{checkout_branch}}"
  - name: install gpg
    yum: name=gpg state=present

  - name: copy backup sql into local repo and encrypt
    copy: 
      src: "/tmp/{{mysql_db_name}}.sql"  
      dest: "/tmp/repos/test-sre/"
      remote_src: yes

  - name: create cron job to perform db backups
    cron:
      name: "{{mysql_db_name}} hourly dump"
      minute: "0"
      hour: "*"
      job: "mysqldump apidb -u {{login_user}} -p{{login_password}} > /tmp/repos/test-sre/$(date +\\%Y\\%m\\%d\\%H\\%M\\%S).sql"


